import Head from 'next/head'
import styles from '../styles/index.module.scss'
import ListedSnippet from "../components/ListedSnippet";
import {useEffect} from "react";
import hljs from 'highlight.js';

export default function Home({container}) {
  let loadedSnippets = [];
  JSON.parse(container).forEach(snippet => {
    loadedSnippets.push(<ListedSnippet key={snippet.props.title} title={snippet.props.title} author={snippet.props.author} language={snippet.props.language} tags={snippet.props.tags} code={snippet.props.code}/>)
  });
  useEffect(() => {
    hljs.highlightAll();
    const search = document.getElementById("search");
    const snippets = document.getElementById("snippets").children;
    const inputHandler = (e) => {
      let searchTerm = e.target.value.toLowerCase();
      for (let i = 0; i < snippets.length; i++) {
        searchTerm.split(" ").forEach((term) => {
          if (term.length === 0) return;
          let title = snippets.item(i).attributes.getNamedItem("title").value.toLowerCase();
          let author = snippets.item(i).attributes.getNamedItem("author").value.toLowerCase();
          let language = snippets.item(i).attributes.getNamedItem("language").value.toLowerCase();
          let tags = snippets.item(i).attributes.getNamedItem("tags").value.toLowerCase();
          let code = snippets.item(i).attributes.getNamedItem("code").value.toLowerCase();
          if (title.includes(term) || author.includes(term) || language.includes(term) || tags.includes(term) || code.includes(term))
            snippets[i].style.display = "block";
          else
            snippets[i].style.display = "none";
        })
      }
    }
    search.addEventListener('input', inputHandler)
    for (let i = 0; i < snippets.length; i++) {
      snippets.item(i).addEventListener('click', () => {
        let open = snippets.item(i).attributes.open;
        open = !open
        snippets.item(i).attributes.open = open;
        snippets.item(i).children.namedItem("snippet").style.display = open ? "block" : "none";
      })
    }
  })
  return (
    <div>
      <Head>
        <title>shorty//snippets</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main>
        <div className={styles["top-bar"]}>
          <h1 className={styles["title"]}><span className={styles["title-small"]}>shorty // </span>snippets</h1>
          <div>
            <input id="search" className={styles["search"]} type="search" placeholder={"search here..."}/>
          </div>
        </div>
        <div id="snippets" className={styles["snippet-list"]}>
          {loadedSnippets}
        </div>
      </main>
    </div>
  )
}

const environment = "production";
const path = environment === "production" ? "https://snippets.shortydev.eu/" : "http://localhost:3000/";

export async function getServerSideProps(context) {
  let container = [];
  let response = await fetch(path + 'snippets/desc.json');
  response = await response.json();
  for (const snippet of JSON.parse(JSON.stringify(response)).snippets) {
    let snip = await fetch(path + 'snippets/' + snippet.path);
    snip = await snip.text();
    container.push(<ListedSnippet key={snippet.id} title={snippet.title} author={snippet.author}
                                  language={snippet.language} tags={snippet.tags} code={snip}/>)
  }
  return {
    props: {
      container: JSON.stringify(container)
    }
  }
}
